### ISSUE TITLE
Adding Fable.Package.SDK confuses IDE

### ISSUE THREAD

**Issue by Lanayx** [fable-compiler/Fable.Package.SDK#9]
I found this issue some time ago and thought it was related to Rider https://youtrack.jetbrains.com/issue/RIDER-118632/F-syntax-highlight-suddenly-stopped-working-in-a-project
But recently I found that Visual Studio gets confused as well 
![image](https://github.com/user-attachments/assets/b1711e0f-5a3c-425d-82e5-6c2aa5bed318)
And when trying to open that highlighted file, it fails with catastrophic failure
![image](https://github.com/user-attachments/assets/2ea09a29-41dc-4002-9435-3997c1863533)

**Comment by MangelMaxime** [comment]
This is strange because Ionide as no problem and build works so `MSBuild` is happy.

I checked with [EasyBuild.PackageReleaseNotes.Tasks](https://github.com/easybuild-org/EasyBuild.PackageReleaseNotes.Tasks) which also customise MSBuild process and that one works.

So perhaps, I am doing something different here. The problem, is to debug it without any log or error is not going to be fun 😅

**Comment by MangelMaxime** [comment]
Someone on Discord mentioned that it is failing with current VS but preview (17.12) works fine with it.

Which seems to point out that the problem is coming from the IDE more than this package implementation.

**Comment by Lanayx** [comment]
The issue is preserved in VS Preview, I created the issue for VS as well: https://developercommunity.visualstudio.com/t/Adding-FablePackageSDK-confuses-Visual/10772429?

**Comment by MangelMaxime** [comment]
This should be fixed by version 1.2.0

**Comment by MangelMaxime** [comment]
Version 1.3.0 improves the fix for this issue, by not touching the File added by the user and instead rely on MSBuild internal target to copy the files only when packaging the package.
